version: '3.8'
services:
  gateway:
    build: gateway
    image: shareit-gateway
    container_name: shareit-gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      SHAREIT_SERVER_URL: http://server:9090

  server:
    build: server
    image: shareit-server
    container_name: shareit-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USER=neonjohn
      - SPRING_DATASOURCE_PASSWORD=19891989
#      - POSTGRES_DB=shareit
#      - POSTGRES_USER=neonjohn
#      - POSTGRES_PASSWORD=19891989

  db:
    image: postgres:14.3-alpine
    container_name: shareit-db
    restart: always
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=neonjohn
      - POSTGRES_PASSWORD=19891989
    volumes:
      - /var/lib/postgresql/data/