CREATE TABLE IF NOT EXISTS users
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                          VARCHAR(64) UNIQUE NOT NULL,
    name                           VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS items
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                           VARCHAR(64),
    description                    VARCHAR(255),
    is_available                   BOOLEAN,
    owner_id                       BIGINT,
    request_id                     BIGINT,
    CONSTRAINT fk_items_owner      FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date                     TIMESTAMP WITHOUT TIME ZONE,
    end_date                       TIMESTAMP WITHOUT TIME ZONE,
    item_id                        BIGINT,
    booker_id                      BIGINT,
    status                         VARCHAR(20),
    CONSTRAINT fk_bookings_item    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_bookings_booker  FOREIGN KEY (booker_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text                           VARCHAR(200),
    item_id                        BIGINT,
    author_id                      BIGINT,
    created                        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT fk_comments_item    FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_comments_author  FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);